name: png_chunks_encode
description: Return a fresh PNG buffer given a set of PNG chunks. Useful in combination with 
  png-chunks-encode to easily modify or add to the data of a PNG file.
version: 1.0.0
homepage: https://github.com/FlutterFans/png_chunks_encode

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  png_chunks_extract: ^1.0.1
